Eljur/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Eljur.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Неверно введён email")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Неверно введён пароль")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        public string Validation { get; set; }

    }
}

Eljur/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Eljur.Models
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage = "Неверно введён email")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Неверно введён пароль")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Пароли не совпадают")]
        [Compare("Password", ErrorMessage = "Пароли не совпадают")]
        [DataType(DataType.Password)]
        [Display(Name = "Подтвердить пароль")]
        public string PasswordConfirm { get; set; }

        public string Validation { get; set; }
    }
}

Eljur/Controllers/DekanatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eljur.Context;
using Eljur.Context.Tables;
using Eljur.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eljur.Controllers
{
    public class DekanatController : Controller
    {
        public dbContext _db;

        public DekanatController(dbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        
        public IActionResult ChooseGroupForSpecialyMark()
        {
            return View(new SpecialyMarkModel() {Semester = new Context.Tables.Semester() });
        }

        [HttpPost]
        public IActionResult ChooseGroupForSpecialyMark(SpecialyMarkModel model)
        {

            var semesterId = model.Semester.Id;
            var semester = _db.Semesters.Include(x => x.SemesterStudents).Include(x=>x.Group).ThenInclude(x=>x.Students).Where(x => x.Id == semesterId).FirstOrDefault();
            var students = semester.Group.Students.OrderBy(x => x.FIO).ToList();
            model.Students = students;

            if (semester.SemesterStudents.ToList().Count() == 0)
            {
                model.SpecialyMark = new List<string>();
                foreach (var student in students)
                {
                    model.SpecialyMark.Add("");
                }
            }
            else
            {
                model.SpecialyMark = semester.SemesterStudents.Select(x => x.SpecialyMark).ToList();
            }

            return View("SpecialyMarkView", model);
        }

        [HttpPost]
        public IActionResult EditSpecialyMark(SpecialyMarkModel model)
        {
            var semesterId = model.Semester.Id;
            var semester = _db.Semesters
                .Include(x => x.SemesterStudents).ThenInclude(x => x.Semester)
                .Include(x => x.SemesterStudents).ThenInclude(x => x.Student)
                .Include(x => x.Group).ThenInclude(x => x.Students).Where(x => x.Id == semesterId).FirstOrDefault();

            var students = semester.Group.Students.OrderBy(x => x.FIO).ToList();
            var counter = 0;
            foreach(var student in students)
            {
                var semesterStudent = semester.SemesterStudents.Where(x => x.Student.Id == student.Id).FirstOrDefault();
                if(semesterStudent is null)
                {
                    semester.SemesterStudents.Add(new EF.Custom.Entities.SemesterStudent() {Semester = semester, Student = student,SpecialyMark = model.SpecialyMark[counter]});
                }
                else
                {
                    semesterStudent.SpecialyMark = model.SpecialyMark[counter];
                }
                counter++;
            }
            _db.SaveChanges();

            return RedirectToAction("Index","Settings");
        }


        public IActionResult ChooseGroupForCheck()
        {
            return View(new Semester());
        }

        [HttpPost]
        public IActionResult ChooseGroupForCheck(Semester semester)
        {

            var sem = _db.Semesters.Include(x => x.Checks).Where(x => x.Id == semester.Id).FirstOrDefault();
            while (sem.Checks.Count() != 13)
            {
                sem.Checks.Add(new Check() { Semester = _db.Semesters.Find(semester.Id), Text = "", Date = default });
                _db.SaveChanges();
            }
            var texts = sem.Checks.Select(x => x.Text).ToList();
            var dates = sem.Checks.Select(x => x.Date).ToList();

            return View("CheckView", new CheckModel { Texts = texts, Dates = dates, SemesterId = sem.Id });
        }

        [HttpPost]
        public IActionResult EditCheck(CheckModel checks)
        {
            var sem = _db.Semesters.Include(x => x.Checks).Where(x => x.Id == checks.SemesterId).FirstOrDefault();

            for (int i = 0; i < checks.Texts?.Count(); i++)
            {
                sem.Checks[i].Text = checks.Texts[i];
            }
            for (int i = 0; i < checks.Dates?.Count(); i++)
            {
                sem.Checks[i].Date = checks.Dates[i];
            }
            _db.SaveChanges();

            if (User.IsInRole("admin")) return RedirectToAction("Index", "Settings");
            return View("Index");
        }


    }
}

Eljur/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eljur.Context;
using Eljur.Context.Tables;
using Eljur.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eljur.Controllers
{
    public class SharedController : Controller
    {
        public dbContext _db;

        public SharedController(dbContext db)
        {
            _db = db;
        }

        public IActionResult ChooseGroupForComments()
        {
            return View(new Semester());
        }

        [HttpPost]
        public IActionResult ChooseGroupForComments(Semester semester)
        {

            var sem = _db.Semesters.Include(x => x.Comments).Where(x => x.Id == semester.Id).FirstOrDefault();
            while(sem.Comments.Count()!=14)
            {
                sem.Comments.Add(new Comment() { Semester = _db.Semesters.Find(semester.Id), DekanDescription = "", TeacherDescription ="" });
                _db.SaveChanges();
            }
            var teachDesc = sem.Comments.Select(x => x.TeacherDescription).ToList();
            var dekanDesc = sem.Comments.Select(x => x.DekanDescription).ToList();

            return View("CommentsView",new CommentsModel { TeacherDescriptions = teachDesc, DekanDescriptions = dekanDesc, SemesterId = sem.Id });
        }

        [HttpPost]
        public IActionResult EditComments(CommentsModel comments)
        {
            var sem = _db.Semesters.Include(x => x.Comments).Where(x => x.Id == comments.SemesterId).FirstOrDefault();

            for (int i = 0; i < comments.DekanDescriptions?.Count(); i++)
            {
                sem.Comments[i].DekanDescription =  comments.DekanDescriptions[i];
            }
            for (int i = 0; i < comments.TeacherDescriptions?.Count(); i++)
            {
                sem.Comments[i].TeacherDescription = comments.TeacherDescriptions[i];
            }
            _db.SaveChanges();

            if (User.IsInRole("admin")) { return RedirectToAction("Index", "Settings"); }
            if (User.IsInRole("dekan")) { return RedirectToAction("Index", "Dekan"); }
            if (User.IsInRole("teacher")) { return RedirectToAction("Index", "Settings"); }


            return RedirectToAction("Index");
        }




    }
}

Eljur/Views/Shared/ChooseGroupForComments.cshtml
@inject Eljur.Context.dbContext _db
@using Microsoft.EntityFrameworkCore;
@model Eljur.Context.Tables.Semester
@{
    ViewData["Title"] = "Выбор группы";
}
<br />
<h2 class="text-muted text-center font-weight-light" style="margin-top:0;">Выберите группу</h2>
<br />
<br />
<hr />
<form asp-controller="Shared" asp-action="ChooseGroupForComments">
    @{
        var list = _db.Semesters.Include(x => x.Group)
              .Select(x => new { Id = x.Id, Name = x.Group.Name + "(Семестр №" + x.Number + ")" }).ToList();
    }
    <div style="margin:0 auto; width:300px;">
        <select class="form-control" asp-for="@Model.Id" asp-items="@(new SelectList(list, "Id", "Name"))"></select>
        <br />
        <div>
            <button class="btn btn-primary" style="width:100%">Далее</button>
        </div>
    </div>
</form>
<hr />

Eljur/Views/Shared/CommentsView.cshtml
@model CommentsModel
@{
    ViewData["Title"] = "Редактирование замечний";
}
<br />
@if (User.IsInRole("dekan"))
{
    <h2 class="text-center text-muted  font-weight-light">Редактирование решений, принятых деканом факультета</h2>
}
else if (User.IsInRole("teacher"))
{
    <h2 class="text-center text-muted  font-weight-light">
        Редактирование замечаний преподавателей кафедр
    </h2>
}
else if (User.IsInRole("admin"))
{
    <h2 class="text-center text-muted  font-weight-light">
        Редактирование замечаний
    </h2>
}
<br />
<br />

<div id="app">
    <form asp-controller="Shared" asp-action="EditComments" style="margin: 0 auto; width:900px;">
        <input asp-for="@Model.SemesterId" value="@Model.SemesterId" type="hidden" />
        <table class="table table-bordered">
            <thead align="center">
                <tr>
                    <th>
                        Замечания преподавателей кафедр
                    </th>
                    <th>
                        Принятые деканом факультета решения
                    </th>
                </tr>
            <tbody>
                @for (int i = 0; i < Model.TeacherDescriptions.Count(); i++)
                {
                <tr>
                    @if (User.IsInRole("admin"))
                    {
                        <td>
                            <input class="form-control" asp-for="@Model.TeacherDescriptions[i]" value="@Model.TeacherDescriptions[i]" type="text" />
                        </td>
                        <td>
                            <input class="form-control" asp-for="@Model.DekanDescriptions[i]" value="@Model.DekanDescriptions[i]" type="text" />
                        </td>
                    }
                    else if (User.IsInRole("teacher"))
                    {
                        <td>
                            <input class="form-control" asp-for="@Model.TeacherDescriptions[i]" value="@Model.TeacherDescriptions[i]" type="text" />
                        </td>
                        <td>
                            <input class="form-control" asp-for="@Model.DekanDescriptions[i]" value="@Model.DekanDescriptions[i]" disabled type="text" />
                        </td>
                    }
                    else if (User.IsInRole("dekan"))
                    {
                        <td>
                            <input class="form-control" asp-for="@Model.TeacherDescriptions[i]" value="@Model.TeacherDescriptions[i]" type="text" disabled />
                        </td>
                        @if (!string.IsNullOrEmpty(Model.TeacherDescriptions[i]))
                        {
                            <td>
                                <input class="form-control" asp-for="@Model.DekanDescriptions[i]" value="@Model.DekanDescriptions[i]" type="text" />
                            </td>
                        }
                        else
                        {
                            <td>
                                <input class="form-control" asp-for="@Model.DekanDescriptions[i]" value="@Model.DekanDescriptions[i]" type="text" disabled />
                            </td>
                        }
                    }
                </tr>
                }
            </tbody>
        </table>
        <button class="btn btn-primary">Сохранить</button>
    </form>
</div>

Eljur/Views/Shared/Login.cshtml
@model LoginViewModel
@{
    Layout = "_NotAuthLayout";
    ViewBag.Title = "Вход";
}
<style>
    body {
  margin: 0;
  padding: 0;
  background-color: #17a2b8;
  height: 100vh;
}
#login .container #login-row #login-column #login-box {
  margin-top: 120px;
  max-width: 600px;
  height: 350px;
  border: 1px solid #9C9C9C;
  background-color: #EAEAEA;
}
#login .container #login-row #login-column #login-box #login-form {
  padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
  margin-top: -85px;
}
</style>
<body>
    <div id="login">
        <h3 class="text-center text-white pt-5">Авторизация</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" method="post" asp-action="Login">
                            <h3 class="text-center text-info">Вход</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Имя пользователя:</label><br>
                                <input type="email" asp-for="@Model.Email" id="username" class="form-control" placeholder="name@example.com">
                                <span asp-validation-for="@Model.Email"></span>
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Пароль:</label><br>
                                <input type="password" asp-for="@Model.Password" id="password" class="form-control" placeholder="**********">
                                <span asp-validation-for="@Model.Password"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-info btn-md" style="width:100%" value="Войти">
                            </div>
                            @*<div id="register-link" class="text-right">
                                <a asp-controller="Account" asp-action="Register" class="text-info">Регистрация</a>
                            </div>*@
                            <div>
                                <span asp-validation-for="@Model.Validation"></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

Eljur/Views/Shared/Register.cshtml
@model RegisterViewModel
@{
    Layout = "_NotAuthLayout";
    ViewBag.Title = "Вход";
}
<h2 class="text-muted text-center" style="margin-top:0;">Регистрация нового пользователя</h2>
<br />

<div style="width: 300px; margin: auto;">
    <form method="post" asp-controller="Account" asp-action="Register">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" placeholder="name@example.com" />
            <span asp-validation-for="Email"></span>
        </div>
        <div class="form-group">
            <label asp-for="Password"></label>
            <input type="password" asp-for="Password" class="form-control" />
            <span asp-validation-for="Password"></span>
        </div>
        <div class="form-group">
            <label asp-for="PasswordConfirm"></label>
            <input type="password" asp-for="PasswordConfirm" class="form-control" />
            <span asp-validation-for="PasswordConfirm"></span>
        </div>
        <div>
            <button type="submit" class="btn btn-block bg-info border-success-600"> <a style="color:white">Регистрация</a></button>
        </div>
        <div>
            <span>Пароль должен быть следующего вида:</span>
            <ul>
                <li>Длина не менее 6 символов</li>
                <li>Хотя бы один символ в нижнем и верхнем регистре</li>
                <li>Небуквенный символ (!,$ и пр.)</li>
            </ul>
        </div>
        <div>
            <span asp-validation-for="@Model.Validation"></span>
        </div>
    </form>
</div>

Eljur/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eljur</title>
    <link rel="stylesheet" href="~/lib/bootstrap-4.5.0-dist/css/bootstrap.css">
    <link href="~/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/daterangepicker.css" />
    <link rel="stylesheet" href="~/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- JS, Popper.js, and jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap-4.5.0-dist/js/bootstrap.min.js"></script>
    @*<script src="~/lib/bootstrap-4.5.0-dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/lib/tables//datatables/datatables.min.js"></script>
    <script src="~/lib/tables/handsontable/languages/ru-RU.min.js"></script>
    <script type="text/javascript" src="~/js/moment.min.js"></script>
    <script type="text/javascript" src="~/js/daterangepicker.min.js"></script>
    <script src="~/js/bootstrap-select.min.js"></script>

    <!--Vue.js-->
    <script src="~/js/vue@2.js"></script>

    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/tables/table-export/html5/dataTables.buttons.min.js"></script>
    <script src="~/lib/tables/table-export/html5/buttons.flash.min.js"></script>
    <script src="~/lib/tables/table-export/html5/jszip.min.js"></script>
    <script src="~/lib/tables/table-export/html5/pdfmake.min.js"></script>
    <script src="~/lib/tables/table-export/html5/vfs_fonts.js"></script>
    <script src="~/lib/tables/table-export/html5/buttons.html5-custom.js"></script>
    <script src="~/lib/tables/table-export/html5/buttons.print.min.js"></script>
    <script src="~/lib/tables/table-filter.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" asp-action="Index" asp-controller="Settings">ElJur</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    @if (User.IsInRole("admin") || User.IsInRole("teacher"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Settings">Добавить посещение<span class="sr-only">(current)</span></a>
                        </li>
                    }
                    @if (User.IsInRole("admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Настройки</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="EducationLevelsView" asp-controller="Settings">Уровни образования<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="EducationDepartmentsView" asp-controller="Settings">Отделения<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="SpecializationsView" asp-controller="Settings">Специализации<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="GroupView" asp-controller="Settings">Группы<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="SemestersView" asp-controller="Settings">Семестры<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="StudentView" asp-controller="Settings">Студенты<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="VisitView" asp-controller="Settings">Посещения<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="SubjectView" asp-controller="Settings">Предметы<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="ThemeView" asp-controller="Settings">Темы<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="TeachersView" asp-controller="Settings">Преподаватели<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="UsersView" asp-controller="Settings">Пользователи<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="ChooseGroupForSpecialyMark" asp-controller="Dekanat">Особые отметки<span class="sr-only">(current)</span></a>
                                <a class="dropdown-item" asp-action="ChooseGroupForCheck" asp-controller="Dekanat">Контроль<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="ChooseGroupForComments" asp-controller="Shared">Замечания<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="ChooseGroupForSr" asp-controller="Settings">График контр. меропр. по см. работе<span class="sr-only">(current)</span></a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-action="ChooseGroupForDateTaskDone" asp-controller="Settings">Отметка о выполнении студентами контр. меропр. по см. работе<span class="sr-only">(current)</span></a>
                            </div>
                        </li>
                    }
                    @if (User.IsInRole("teacher"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="VisitView" asp-controller="Settings">Посещения<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ChooseGroupForComments" asp-controller="Shared">Замечания<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ChooseGroupForSr" asp-controller="Settings">График контр. меропр. по см. работе<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ChooseGroupForDateTaskDone" asp-controller="Settings">Отметка о выполнении студентами контр. меропр. по см. работе<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ThemeView" asp-controller="Settings">Темы<span class="sr-only">(current)</span></a>
                        </li>
                    }
                    @if (User.IsInRole("dekanat"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ChooseGroupForSpecialyMark" asp-controller="Dekanat">Особые отметки<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ChooseGroupForCheck" asp-controller="Dekanat">Контроль<span class="sr-only">(current)</span></a>
                        </li>
                    }
                    @if (User.IsInRole("dekan"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="ChooseGroupForComments" asp-controller="Shared">Принятые решения<span class="sr-only">(current)</span></a>
                        </li>
                    }
                </ul>

                <span class="navbar-text">
                    <label style="color:white; font-weight:normal; padding-right: 9px;">@User.Identity.Name</label>
                    <a asp-controller="Account" asp-action="Logout" style="color:white; font-weight:bold;" class="btn btn-danger">Выйти</a>
                </span>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Eljur - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>

Eljur/Views/Shared/_NotAuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eljur</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3 navbar-dark bg-dark">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Clients"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="NewWork"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>