Eljur/Models/VisitViewModel.cs
using Eljur.Context.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eljur.Models
{
    public class VisitViewModel
    {
        public DateTime Date { get; set; }
        public int SubjectId { get; set; }
        public int GroupId { get; set; }

        public ChoosePropertyVisit Input { get; set; }
        public VisitGroupForColumnModel Output { get; set; }
    }
}

Eljur/Controllers/VisitController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Eljur.Context;
using Eljur.Context.Tables;
using Eljur.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OfficeOpenXml;

namespace Eljur.Controllers
{
    [Authorize(Roles = "admin, teacher, dekan, dekanat")]
    public partial class VisitController : Controller
    {
        dbContext _db;
        public VisitController(dbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        //views
        public IActionResult ChooseGroupView()
        {
            var model = new ChoosePropertyVisit();
            return View(model);
        }
        public IActionResult ChooseSubjectView()
        {
            return View();
        }
        public IActionResult ChooseTimeView()
        {
            return View();
        }
        public IActionResult NoVisits(ChoosePropertyVisit model)
        {
            return View(model);
        }

        public IActionResult ChooseGroup(ChoosePropertyVisit model)
        {
            return View("ChooseSubjectView", model);
        }
        public IActionResult ChooseSubject(ChoosePropertyVisit input)
        {
            input.Group = _db.Group.Include(x => x.Students).Where(x => x.Id == input.Group.Id).FirstOrDefault();
            input.Subject = _db.Subject.Include(x => x.Themes).Where(x => x.Id == input.Subject.Id).FirstOrDefault();

            var visits = new List<VisitModify>();
            for (int j = 0; j < input.Group.Students.Count(); j++) visits.Add(new VisitModify());

            var output = new VisitGroupForColumnModel() { VisitsModify = visits };

            var model = new VisitViewModel() { Input = input, Output = output, Date = DateTime.Now };

            return View("VisitsView", model);
        }
        /// <summary>
        /// Добавление посещений
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public IActionResult AddVisit(VisitViewModel model)
        {
            var date = model.Date;

            var saved = HttpContext.Session.GetString("SessionStorageThemes");
            var storage = new List<SessionStorageThemes>();
            if (storage != null)
            {
                storage = JsonConvert.DeserializeObject<List<SessionStorageThemes>>(saved);
            }

            var themeVisits = new List<ThemeVisit>();
            foreach (var savedTheme in storage)
            {
                var theme = _db.Theme.Include(x => x.ThemeGroup).Include(x => x.Subject).ThenInclude(x => x.Semester).Where(x => x.Id == savedTheme.ThemeId).FirstOrDefault();

                theme.ThemeGroup.UsedHours = savedTheme.ThemeGroup.UsedHours;
                var hoursPerVisit = savedTheme.Reserved;
                var typeSubject = theme.Type;
                var themeVisit = new ThemeVisit() { HoursPerVisit = hoursPerVisit, Theme = theme, TypeSubject = typeSubject };

                themeVisits.Add(themeVisit);
            }

            var visit = new GroupVisit()
            {
                Date = date,
                ThemeVisits = themeVisits,
                Subject = _db.Subject.Find(model.SubjectId),
                Group = _db.Group.Find(model.GroupId),
                Semester = _db.Subject.Include(x => x.Semester).Where(x => x.Id == model.SubjectId).FirstOrDefault().Semester,
                Theme = themeVisits.FirstOrDefault().Theme
            };
            _db.GroupVisit.Add(visit);

            foreach (var visitModify in model.Output.VisitsModify)
            {
                var studentVisit = new StudentVisit()
                {
                    TypeVisit = visitModify.TypeVisit,
                    Student = _db.Student.Find(visitModify.StudentId),
                    GroupVisit = visit,
                    Subject = _db.Subject.Find(model.SubjectId),
                    Theme = visit.ThemeVisits.FirstOrDefault().Theme
                };
                _db.StudentVisit.Add(studentVisit);
                visit.StudentVisits.Add(studentVisit);
                visit.Theme.StudentVisits.Add(studentVisit);
            }

            _db.SaveChanges();
            return View("VisitAddedView");

        }
        /// <summary>
        /// Редактирование посещения
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public IActionResult EditGroupVisit(ChoosePropertyVisit model)
        {
            model.Group = _db.Group.Find(model.Group.Id);

            var visits = _db.GroupVisit
                .Include(x => x.StudentVisits)
                .ThenInclude(x => x.Student)
                .Include(x => x.Subject)
                .Include(x => x.Group)
                .Include(x => x.ThemeVisits)
                .ThenInclude(x => x.Theme)
                .Where(x => x.Group.Id == model.Group.Id).ToList();

            var output = new GroupVisitView()
            {
                Semester = model.Semester,
                GroupId = model.Group.Id,
                Visits = visits,
                Filter = new Filter() { From = visits.Count == 0 ? DateTime.Now : visits.Min(x => x.Date), Before = visits.Count == 0 ? DateTime.Now : visits.Max(x => x.Date) }
            };

            return View("VisitTableView", output);
        }
        public IActionResult EditStudentVisitView(int id)
        {
            var model = _db.StudentVisit
                .Include(x => x.Student)
                .Include(x => x.GroupVisit)
                .ThenInclude(x => x.Subject)
                .Include(x => x.GroupVisit)
                .ThenInclude(x => x.Group)
                .Where(x => x.Id == id)
                .FirstOrDefault();

            return View("EditVisitView", model);
        }
        [HttpPost]
        public IActionResult EditStudentVisitView(StudentVisit model, int subjectId, int groupId)
        {
            var visit = _db.StudentVisit.Find(model.Id);
            visit.TypeVisit = model.TypeVisit;
            _db.SaveChanges();

            var visits = _db.GroupVisit
                .Include(x => x.StudentVisits)
                .ThenInclude(x => x.Student)
                .Include(x => x.Subject)
                .Include(x => x.Group)
                .Include(x => x.ThemeVisits)
                .Where(x => ((x.Subject.Id == subjectId)
                        && (x.StudentVisits.FirstOrDefault().Student.Group.Id == groupId)))
                .ToList();

            var output = new GroupVisitView()
            {
                GroupId = groupId,
                SubjectId = subjectId,
                Visits = visits,
                Filter = new Filter() { From = visits.Min(x => x.Date), Before = visits.Max(x => x.Date) }
            };

            return View("VisitTableView", output);
        }
        /// <summary>
        /// Удалить посещение
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult RemoveStudentVisit(int id, int groupId, int subjectId)
        {
            var visit = _db.StudentVisit.Find(id);
            _db.StudentVisit.Remove(visit);
            _db.SaveChanges();

            var visits = _db.GroupVisit
                             .Include(x => x.StudentVisits)
                             .ThenInclude(x => x.Student)
                             .Include(x => x.Subject)
                             .Include(x => x.Group)
                             .Include(x => x.ThemeVisits)
                             .Where(x => ((x.Subject.Id == subjectId)
                             && (x.StudentVisits.FirstOrDefault().Student.Group.Id == groupId)))
                             .ToList();

            var output = new GroupVisitView()
            {
                GroupId = groupId,
                SubjectId = subjectId,
                Visits = visits,
                Filter = new Filter() { From = visits.Min(x => x.Date), Before = visits.Max(x => x.Date) }
            };

            return View("VisitTableView", output);

        }
        /// <summary>
        /// Отображаем настройку "Посещения"
        /// </summary>
        /// <param name="model"></param>
        /// <param name="action"></param>
        /// <returns></returns>
        public IActionResult VisitView(ChoosePropertyVisit model, string action)
        {
            model.Group = _db.Group.Find(model.Group.Id);

            var group = _db.Group
                .Include(x => x.Semesters)
                .ThenInclude(x => x.GroupVisits)
                .Include(x => x.Semesters)
                .ThenInclude(x => x.Subjects)
                .Where(x => x.Id == model.Group.Id)
                .FirstOrDefault();

            var subject = group.Semesters.Where(x => x.Number == model.Semester).FirstOrDefault()?.Subjects.ToList();

            if ((subject is null) || (subject.Count() == 0))
            {
                return View("NoVisits", model);
            }
            else
            if ((subject is null) && (action != "create-for-group"))
            {
                return View("NoVisits", model);
            }

            switch (action)
            {
                case "create": { return GetExcel(model, allSubjects: false); }
                case "edit": { return EditGroupVisit(model); }
                case "create-for-group": { return GetExcel(model, allSubjects: true); }
            }
            return View("VisitView");
        }
        /// <summary>
        /// Создаём excel
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>

Eljur/Views/Visit/ChooseGroupView.cshtml
@inject Eljur.Context.dbContext _db
@using Microsoft.EntityFrameworkCore;
@model ChoosePropertyVisit
@{
    ViewData["Title"] = "Выбор группы";
}
<br />
<h2 class="text-muted text-center font-weight-light" style="margin-top:0;">Выберите группу</h2>
<br />
<br />
<hr />
<form asp-controller="Visit" asp-action="ChooseGroup">
    <div style="margin:0 auto; width:300px;">
        <div class="row">
            <select class="form-control" asp-for="@Model.Group.Id" asp-items="@(new SelectList(_db.Group, "Id", "Name"))"></select>
        </div>
        <br />
        <div class="row">
            <button class="btn btn-primary" style="width:100%">Далее</button>
        </div>
    </div>
</form>
<hr />

Eljur/Views/Visit/ChooseSubjectView.cshtml
@inject Eljur.Context.dbContext _db
@using Microsoft.EntityFrameworkCore;
@model ChoosePropertyVisit
@{
    ViewData["Title"] = "Выбор предмета";
}
<br />
<h2 class="text-muted text-center font-weight-light" style="margin-top:0;">Выберите предмет</h2>
<br />
<br />
<hr />
<form asp-controller="Visit" asp-action="ChooseSubject">
    <input asp-for="@Model.Group.Id" type="hidden"/>
    <div style="margin:0 auto; width:300px;">
        <div class="row">
            <select class="form-control" asp-for="@Model.Subject.Id" asp-items="@(new SelectList(_db.Subject
                      .Include(x => x.Semester).ThenInclude(x => x.Group)
                      .Where(x => x.Group.Id == Model.Group.Id)
                      .Select(x => new { Id = x.Id, Name = x.Name + "(Семестр №" + x.Semester.Number + ")" })
                      .ToList(), "Id", "Name"))"></select>
        </div>
        <br />
        <div class="row">
            <button class="btn btn-primary" style="width:100%">Далее</button>
        </div>
    </div>
</form>
<hr />

Eljur/Views/Visit/EditVisitView.cshtml
@inject Eljur.Context.dbContext _db
@model Eljur.Context.Tables.StudentVisit
@{
    ViewData["Title"] = "EditVisitView";
}
<br />
<h2 class="text-muted text-center font-weight-light" style="margin-top:0;">Редактировать посещение студента [@Model.Student.FIO]</h2>
<br />
<br />
<hr />
<form asp-controller="Visit" asp-action="EditStudentVisitView" method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <input name="subjectId" value="@Model.GroupVisit.Subject.Id" type="hidden" />
    <input name="groupId" value="@Model.GroupVisit.Group.Id" type="hidden" />
    <div style="margin:0 auto; width:300px;">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label>Тип занятия</label>
                    <select class="form-control" asp-for="@Model.TypeVisit" asp-items="@Html.GetEnumSelectList(typeof(Eljur.Context.Tables.TypeVisitEnum))"></select>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <button class="btn btn-primary" style="width:100%">Обновить</button>
        </div>
    </div>
</form>

Eljur/Views/Visit/NoVisits.cshtml
@model ChoosePropertyVisit
@{
    ViewData["Title"] = "NoVisit";
}
<br />
<br />
<br />
<br />

<h4 style="text-align:center">К группе [@Model.Group.Name] не прикреплён предмет [@Model.Subject.Name] 🙌</h4>
<br />
<div style="margin: 0 auto;width:200px;">
    <a class="btn btn-success" asp-action="VisitView" asp-controller="Settings" style="width:100%">Назад</a>
</div>

Eljur/Views/Visit/VisitAddedView.cshtml
@{
    ViewData["Title"] = "VisitAddedView";
}
<br />
<br />
<br />
<br />

<h4 style="text-align:center">Посещение успешно добавлено ✅</h4>
<br />
<script>
    setTimeout(redirect, 2000);
    function redirect() {
        document.location.href="/Settings/Index"
    }
</script>

Eljur/Views/Visit/VisitTableView.cshtml
@model GroupVisitView
@{
    ViewData["Title"] = "VisitTableView";
}
<br />
<h2 class="text-muted text-center font-weight-light">Посещения группы @Model?.Visits.FirstOrDefault()?.Group.Name</h2>
<br />
<form asp-action="VisitFilter" asp-controller="Visit" method="post" style="background: darkcyan;padding: 30px;border-radius: 3px;">
    <input hidden asp-for="@Model.GroupId" />
    <input hidden asp-for="@Model.SubjectId" />
    <input hidden asp-for="@Model.Semester" />
    <h4 style="color: white;
        text-align: center;">
        Фильтр
    </h4>
    <hr style="background: yellowgreen;" />
    <div class="filter">
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label style="color:white">От</label>
                    <input asp-for="@Model.Filter.From" class="form-control" type="date" />
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label style="color:white">До</label>
                    <input asp-for="@Model.Filter.Before" class="form-control" type="date" />
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label style="color:white">Фамилия</label>
                    <input asp-for="@Model.Filter.LastName" class="form-control" type="text" placeholder="Иванов" />
                </div>
            </div>
            <div class="col-2">
                <button class="btn btn-info" style="width:100%" name="action" value="submit">Применить</button>
            </div>
            <div class="col-2">
                <button class="btn btn-info" style="width:100%" name="action" value="reset">Сброс</button>
            </div>
        </div>
    </div>
</form>

<br />
<br />
<table class="table table-bordered" id="tableid" style="text-align:center">
    <thead>
        <tr>
            <th>Дата</th>
            <th>Студент</th>
            <th>Предмет</th>
            <th>Тема</th>
            <th>Тип посещения</th>
            <th>Вид занятия</th>
            @if (User.IsInRole("admin"))
            {
                <th>Действие</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model.Visits)
        {
            foreach (var studentVisit in group.StudentVisits)
            {
        <tr>
            <td>@group.Date.ToString("dd.MM.yyyy")</td>
            <td>@studentVisit.Student.FIO</td>
            <td>@studentVisit.Subject.Name</td>
            <td>
                <ul>
                    @foreach (var themeVisit in studentVisit.GroupVisit.ThemeVisits)
                    {
                        <li>@themeVisit.Theme.Name</li>

                    }
                </ul>
            </td>
            <td>
                <ul>
                    @foreach (var themeVisit in studentVisit.GroupVisit.ThemeVisits)
                    {
                        <li>@Html.DisplayFor(x => themeVisit.TypeSubject)</li>
                    }
                </ul>
            </td>
            <td>@Html.DisplayFor(x => studentVisit.TypeVisit)</td>
            @if (User.IsInRole("admin"))
            {
                <td align="center">
                    <a class="btn btn-primary" asp-action="RemoveStudentVisit" asp-controller="Visit" asp-route-id="@studentVisit.Id"
                       asp-route-groupId="@studentVisit.Student.Group.Id" asp-route-subjectId="@group.Subject.Id" title="Удалить выбранную запись">❌</a>
                    <a class="btn btn-primary" asp-action="EditStudentVisitView" asp-controller="Visit" asp-route-id="@studentVisit.Id" title="Изменить выбранную запись">✏️</a>
                </td>
            }
        </tr>
            }
        }
    </tbody>
</table>

Eljur/Views/Visit/VisitsView.cshtml
@model VisitViewModel
@{
    ViewData["Title"] = "Посещения";
}
<br />
<h2 class="text-muted text-center font-weight-light" style="margin-top:0;">Добавление посещения</h2>
<br />
<h6 class="text-muted text-center font-weight-light">Группа: <b>@Model.Input.Group.Name</b>. Предмет: <b>@Model.Input.Subject.Name</b>.</h6>
<br />
@{int events = Convert.ToInt32(Model.Input.Time / 2);}

@*Vue - элемент*@
<div id="app">
    <form asp-controller="Visit" asp-action="AddVisit">
        <input asp-for="@Model.SubjectId" value="@Model.Input.Subject.Id" type="hidden" />
        <input asp-for="@Model.GroupId" value="@Model.Input.Group.Id" type="hidden" />
        <input asp-for="@Model.Input.Time" type="hidden" />
        <table class="table table-bordered">
            <thead align="center">
                <tr>
                    <th rowspan="2">Студент</th>
                    <th colspan="@events">Дата:   <input asp-for="@Model.Date" type="date" placeholder="Дата" /> </th>
                </tr>
                <tr>
                    <th>
                        <div class="row">
                            <div class="col">
                                Тип занятия:
                                <select id='@($"TypeSubject_1")' class="form-control" asp-for="@Model.Output.TypeSubject"
                                        asp-items="@Html.GetEnumSelectList(typeof(Eljur.Context.Tables.TypeSubjectEnum))" onchange="GetThemesList(1)" v-on:change="{{reset()}}"></select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                Тема:
                                <select id='@($"Theme_1")' class="form-control" asp-for="@Model.Output.ThemeId" required v-on:change="{{select(themeId, true)}}" v-model="themeId">
                                    <option disabled selected value=''>Не выбрано</option>
                                </select>
                            </div>
                        </div>

                        <div v-if="visibleAdditional" id="additional-theme">

                            <div class="d-inline">
                                <br />
                                <label>Список доп. тем (осталось {{parseFloat(timeInVisit-reservedTime).toFixed(1)}}ч. из {{timeInVisit}}ч.)</label>
                                <a type="button" data-toggle="modal" data-target="#modal" v-on:click="{{calculateModal()}}" v-if="!isVisibleAddVisit">🔽</a>
                            </div>

                            <div v-for="theme in selectedThemes">
                                <hr />
                                <div class="row">
                                    <div class="col">
                                        <h6>Тема: {{theme.name}}</h6>
                                        <h6>Использовано ч.: {{theme.time}}</h6>
                                        </div>
                                        <div class="col">
                                            @*                                        <button type="button" class="btn btn-primary" title="Изменить выбранную запись">✏️</button>*@
                                            <button type="button" class="btn btn-primary" title="Удалить выбранную запись" v-on:click="{{removeTheme(theme)}}">❌</button>
                                        </div>
                                    </div>
                                <hr />
                            </div>
                        </div>

            <tbody>
                @{ var counter = 0;}
                @foreach (var student in Model.Input.Group.Students.OrderBy(x => x.FIO))
                {
                    <tr>
                        <td>@student.FIO</td>
                        <td>
                            <input asp-for="@Model.Output.VisitsModify[counter].StudentId" value="@student.Id" type="hidden" />

                            <select class="form-control" asp-for="@Model.Output.VisitsModify[counter].TypeVisit"
                                    asp-items="@Html.GetEnumSelectList(typeof(Eljur.Context.Tables.TypeVisitEnum))">
                            </select>
                        </td>
                    </tr>
                    counter++;
                }
            </tbody>
        </table>
        <button v-if="isVisibleAddVisit" class="btn btn-success">Добавить</button>
    </form>


    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Добавить тему</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Тип занятия:
                    <select id='@($"TypeSubject_Modal")' class="form-control"
                            asp-items="@Html.GetEnumSelectList(typeof(Eljur.Context.Tables.TypeSubjectEnum))" v-on:change="{{calculateModal()}}"></select>
                    Тема:
                    <select class="form-control" id="modalThemes" v-model="modalThemeId">
                        <option disabled selected value=''>Не выбрано</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary" required v-on:click="{{select(modalThemeId, false)}}" data-dismiss="modal">Добавить</button>
                </div>
            </div>
        </div>
    </div>

</div>
<script>

    //начальная инициализация
    $(document).ready(function () {
        GetThemesList(1);

        //максимум за раз можем списать 2 часа
        var app = new Vue({

            el: '#app',
            data: {
                timeInVisit: 2,
                reservedTime: 0.0,
                themeId: "",
                modalThemeId: "",
                groupId: "",
                selectedThemes: [],
                visibleModal: false,
                isVisibleAddVisit: false,
            },
            computed: {
                visibleAdditional: function () {
                    return (this.reservedTime == 0) ? false : true;
                },
                isAddidional: function () {
                    this.isVisibleAddVisit();
                },
                allowAdd: function () {
                    this.isVisibleAddVisit();
                }
            },
            methods: {
                select: function (id, isFirstSelect) {
                    if (isFirstSelect) {
                        this.reset();
                        console.log(id);
                        let allowedTime = parseFloat(app.timeInVisit - app.reservedTime).toFixed(1).toString().replace(".", ",");
                        fetch("\SaveSelectedThemeToSession?themeId=" + id + "&allowedTime=" + allowedTime + "&isFirst=true")
                            .then(function (response) {
                                return response.text();
                            })
                            .then(function (text) {
                                let reservedTime = Number(parseFloat(app.reservedTime + parseFloat(text)).toFixed(1));
                                app.reservedTime = reservedTime;

                            });
                    }
                    else {
                        let allowedTime = (app.timeInVisit - app.reservedTime).toString().replace(".", ",");
                        fetch("\SaveSelectedThemeToSession?themeId=" + id + "&allowedTime=" + allowedTime + "&isFirst=false")
                            .then(function (response) {
                                return response.text();
                            })
                            .then(function (text) {

                                let reservedTime = Number(parseFloat(app.reservedTime + parseFloat(text)).toFixed(1));
                                app.reservedTime = reservedTime;

                                let time = Number((parseFloat(text)).toFixed(1));

                                //добавлять на бэке
                                fetch("\GetThemeName?id=" + id)
                                    .then(function (response) {
                                        return response.text();
                                    })
                                    .then(function (text) {
                                        app.selectedThemes.push({ id: id, name: text, time: time });
                                    });

                            });

                    }
                    @*+ "&groupId=" + groupId + "&subjectId=" + subjectId + *@
                },
                reset: function () {
                    //очистку на бэке
                    this.reservedTime = 0;
                    this.selectedThemes = [];
                    this.clearSession();
                },
                removeTheme: async function (theme) {
                    await this.clearItemInSession(theme.id);

                    var arr = app.selectedThemes;
                    var index = arr.indexOf(theme);
                    this.reservedTime -= arr[index].time;
                    arr.splice(index, 1);
                    //удалять на бэке
                },
                calculateModal: function () {
                    let typeSubject = $("#TypeSubject_Modal").val();
                    let subjectId = $("#SubjectId").val();
                    fetch("GetThemesListFromSession/?typeSubject=" + typeSubject + "&subjectId=" + subjectId)
                        .then(function (response) {
                            return response.text();
                        })
                        .then(function (text) {
                            $("#modalThemes").empty();
                            $("#modalThemes").append(text);
                        });
                },
                clearSession: function () {
                    fetch("ClearSession");
                },
                clearItemInSession: async function (id) {
                    await fetch("ClearItemInSession/?id=" + id)
                },
                overflowTimeCheck: function () {
                    fetch("\IsAllowAddVisit?subjectId=" + $("#SubjectId").val())
                        .then(function (response) {
                            return response.text();
                        })
                        .then(function (text) {
                            var isAllow = text == 'true';
                            app.isVisibleAddVisit = isAllow;
                        });
                }

            },
            watch: {
                reservedTime: function () {
                    console.log("reservedTime changed");
                    this.overflowTimeCheck();
                }
            },
        })
    })

    //загружаем при помощи get запроса список доступных тем
    async function GetThemesList(i) {
        let typeSubject = $("#TypeSubject_" + i).val();
        let subjectId = $("#SubjectId").val();

        let response = await fetch("GetThemesList/?typeSubject=" + typeSubject + "&subjectId=" + subjectId );
        if (response.ok) {
            $("#Theme_" + i).empty();
            $("#Theme_" + i).append(await response.text());
        }
    }
</script>